services:
  db:
    image: postgres:17
    container_name: sf_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sf_bd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - sf_pgdata:/var/lib/postgresql/data

  backend:
    image: oceansecurity/sf_backend:latest
    container_name: sf_backend
    restart: unless-stopped
    environment:
      DEBUG: "False"
      SECRET_KEY: "uU9mQ4wz6Qy8tKf2G1xv7Nn3aL5pR0sVjHcE2dZbY6mT8qWf"
      ALLOWED_HOSTS: "89.117.146.163"
      CORS_ALLOWED_ORIGINS: "http://89.117.146.163"
      DB_NAME: sf_bd
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: "5432"
    volumes:
      - sf_media:/app/media
    depends_on:
      - db

  frontend:
    image: oceansecurity/sf_frontend:latest
    container_name: sf_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sf_pgdata:
  sf_media:
