# Generated by Django 5.2.1 on 2025-09-03 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('denominativo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='CoreFisica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='CoreFisica.instalacion')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('rotativo', models.CharField(blank=True, max_length=10, null=True)),
                ('mes', models.CharField(blank=True, max_length=2, null=True)),
                ('anio', models.CharField(blank=True, max_length=4, null=True)),
                ('dia_1', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_2', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_3', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_4', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_5', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_6', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_7', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_8', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_9', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_10', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_11', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_12', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_13', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_14', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_15', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_16', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_17', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_18', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_19', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_20', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_21', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_22', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_23', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_24', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_25', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_26', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_27', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_28', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_29', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_30', models.CharField(blank=True, max_length=10, null=True)),
                ('dia_31', models.CharField(blank=True, max_length=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreFisica.cliente')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreFisica.horario')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreFisica.instalacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreFisica.persona')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreFisica.puesto')),
            ],
        ),
    ]
