# Generated by Django 5.2.1 on 2026-01-23 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('FIJO', 'FIJO'), ('FRANCO', 'FRANCO'), ('SACAFRANCO', 'SACAFRANCO'), ('EVENTUAL', 'EVENTUAL')], max_length=15, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['nombre_comercial'], name='CoreFisica__nombre__b65ad3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='CoreFisica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horas_trabajo', models.IntegerField(default=0)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='CoreFisica.instalacion')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(default=1)),
                ('anio', models.PositiveSmallIntegerField(default=2026)),
                ('rotativo', models.BooleanField(default=False)),
                ('dias_turno_dia', models.IntegerField(default=0, help_text='Cantidad de días en turno DÍA')),
                ('dias_turno_noche', models.IntegerField(default=0, help_text='Cantidad de días en turno NOCHE')),
                ('dias_franco', models.IntegerField(default=0, help_text='Cantidad de días FRANCO')),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreFisica.cliente')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreFisica.horario')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreFisica.instalacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreFisica.persona')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreFisica.puesto')),
            ],
            options={
                'unique_together': {('persona', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(blank=True, choices=[('D', 'Día'), ('N', 'Noche'), ('F', 'Franco'), ('NB', 'Noche Base Disponible'), ('SC', 'Saca Vacaciones')], max_length=2, null=True)),
                ('dia_numero', models.IntegerField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='CoreFisica.asignacion')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('asignacion', 'fecha')},
            },
        ),
    ]
