# Generated by Django 5.2.1 on 2026-01-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='cantidad_guardias',
            field=models.IntegerField(default=0),
        ),
    ]
