# Generated by Django 5.2.1 on 2025-09-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('FIJO', 'FIJO'), ('FRANCO', 'FRANCO')], max_length=10, null=True),
        ),
    ]
