# Generated by Django 5.2.1 on 2026-01-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0002_puesto_cantidad_guardias'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='descripcion_sistema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puesto',
            name='sistema',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
