# Generated by Django 5.2.1 on 2025-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0002_persona_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='asignacion',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
