# Generated by Django 5.2.1 on 2026-01-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0003_puesto_descripcion_sistema_puesto_sistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='sistema',
        ),
        migrations.AddField(
            model_name='puesto',
            name='dias',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='puesto',
            name='turno_dia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puesto',
            name='turno_noche',
            field=models.BooleanField(default=False),
        ),
    ]
