# Generated by Django 5.2.1 on 2025-10-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0003_alter_asignacion_options_asignacion_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=10, null=True),
        ),
    ]
