# Generated by Django 5.2.1 on 2026-01-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0004_remove_puesto_sistema_puesto_dias_puesto_turno_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='turno_dia',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='turno_noche',
        ),
        migrations.AddField(
            model_name='puesto',
            name='turno',
            field=models.CharField(choices=[('dia', 'Día'), ('noche', 'Noche')], default='dia', max_length=10),
        ),
    ]
