# Generated by Django 5.2.1 on 2026-01-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0004_asignacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacion',
            name='codigo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
