# Generated by Django 5.2.1 on 2026-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0005_remove_puesto_turno_dia_remove_puesto_turno_noche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='descripcion_sistema',
        ),
        migrations.AddField(
            model_name='puesto',
            name='resumen',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
