# Generated by Django 5.2.1 on 2026-01-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0005_remove_instalacion_codigo_cliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('FIJO', 'FIJO'), ('FRANCO', 'FRANCO'), ('SACAFRANCO', 'SACAFRANCO'), ('EVENTUAL', 'EVENTUAL')], max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre_comercial'], name='CoreFisica__nombre__b65ad3_idx'),
        ),
    ]
