# Generated by Django 5.2.1 on 2026-01-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0006_alter_persona_tipo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together={('persona', 'puesto', 'mes', 'anio')},
        ),
        migrations.AddField(
            model_name='puesto',
            name='horas_trabajo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='anio',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='mes',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='rotativo',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_1',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_10',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_11',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_12',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_13',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_14',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_15',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_16',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_17',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_18',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_19',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_2',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_20',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_21',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_22',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_23',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_24',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_25',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_26',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_27',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_28',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_29',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_3',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_30',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_31',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_4',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_5',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_6',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_7',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_8',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dia_9',
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(blank=True, choices=[('D', 'Día'), ('N', 'Noche')], max_length=1, null=True)),
                ('codigo_cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(choices=[('NORMAL', 'Normal'), ('FRANCO', 'Franco'), ('DISPONIBLE', 'Disponible')], default='NORMAL', max_length=15)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='CoreFisica.asignacion')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('asignacion', 'fecha')},
            },
        ),
    ]
