# Generated by Django 5.2.1 on 2026-01-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0006_remove_puesto_descripcion_sistema_puesto_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='resumen',
            field=models.CharField(blank=True, help_text='Resumen de la asignación', max_length=255, null=True),
        ),
    ]
