# Generated by Django 5.2.1 on 2026-01-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0007_alter_asignacion_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacion',
            name='nombre',
        ),
    ]
