# Generated by Django 5.2.1 on 2026-01-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0007_asignacion_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='dias_franco',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dias_turno_dia',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='dias_turno_noche',
        ),
    ]
