# Generated by Django 5.2.1 on 2026-01-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0008_remove_instalacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
