# Generated by Django 5.2.1 on 2026-01-30 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0009_remove_asignacion_resumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('mon', models.CharField(blank=True, max_length=4)),
                ('tue', models.CharField(blank=True, max_length=4)),
                ('wed', models.CharField(blank=True, max_length=4)),
                ('thu', models.CharField(blank=True, max_length=4)),
                ('fri', models.CharField(blank=True, max_length=4)),
                ('sat', models.CharField(blank=True, max_length=4)),
                ('sun', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_semanales', to='CoreFisica.puesto')),
            ],
        ),
        migrations.DeleteModel(
            name='AsignacionCalendario',
        ),
        migrations.AddIndex(
            model_name='asignacionsemanal',
            index=models.Index(fields=['week_start'], name='CoreFisica__week_st_5db15f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionsemanal',
            unique_together={('puesto', 'week_start')},
        ),
    ]
