# Generated by Django 5.2.1 on 2026-01-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0009_instalacion_codigo'),
    ]

    operations = [
    ]
