# Generated by Django 5.2.1 on 2026-01-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0010_asignacionsemanal_delete_asignacioncalendario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
