# Generated by Django 5.2.1 on 2026-01-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0010_auto_20260122_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacion',
            name='codigo',
        ),
    ]
