# Generated by Django 5.2.1 on 2026-01-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0011_remove_instalacion_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='codigo_cliente',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='estado',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='dia_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='turno',
            field=models.CharField(blank=True, choices=[('D', 'Día'), ('N', 'Noche'), ('F', 'Franco'), ('NB', 'Noche Base Disponible'), ('SC', 'Saca Vacaciones')], max_length=2, null=True),
        ),
    ]
