# Generated by Django 5.2.1 on 2026-02-02 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0011_asignacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Cédula: sólo dígitos, máximo 10', regex='^\\d{1,10}$')]),
        ),
    ]
