# Generated by Django 5.2.1 on 2026-02-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0012_alter_persona_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='rotativo',
        ),
    ]
