# Generated by Django 5.2.1 on 2026-01-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0012_remove_asistencia_codigo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='dias_franco',
            field=models.IntegerField(default=0, help_text='Cantidad de días FRANCO'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='dias_turno_dia',
            field=models.IntegerField(default=0, help_text='Cantidad de días en turno DÍA'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='dias_turno_noche',
            field=models.IntegerField(default=0, help_text='Cantidad de días en turno NOCHE'),
        ),
    ]
