# Generated by Django 5.2.1 on 2026-01-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0013_asignacion_dias_franco_asignacion_dias_turno_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='denominativo',
        ),
    ]
