# Generated by Django 5.2.1 on 2026-01-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0014_remove_horario_denominativo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together={('persona', 'mes', 'anio')},
        ),
    ]
