# Generated by Django 5.2.1 on 2026-01-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0015_alter_asignacion_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={},
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='orden',
        ),
    ]
