# Generated by Django 5.2.1 on 2026-02-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0015_remove_cliente_codigo_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
