# Generated by Django 5.2.1 on 2026-02-06 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0016_instalacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='RUC: 10 o 13 dígitos', regex='^\\d{10}(\\d{3})?$')]),
        ),
    ]
