# Generated by Django 5.2.1 on 2026-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0017_cliente_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='turno',
            field=models.CharField(choices=[('dia', 'Diurno'), ('noche', 'Nocturno')], default='dia', max_length=10),
        ),
    ]
