# Generated by Django 5.2.1 on 2026-02-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0018_alter_puesto_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='turno',
            field=models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], default='Diuno', max_length=10),
        ),
    ]
