# Generated by Django 5.2.1 on 2026-02-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0020_alter_puesto_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
    ]
