# Generated by Django 5.2.1 on 2026-02-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0022_turno_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='turno',
            field=models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], default='Diurno', max_length=10),
        ),
    ]
