# Generated by Django 5.2.1 on 2026-02-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0023_alter_puesto_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'L'), (2, 'M'), (3, 'X'), (4, 'J'), (5, 'V'), (6, 'S'), (7, 'D')])),
                ('horas', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='CoreFisica.puesto')),
            ],
            options={
                'verbose_name': 'Horario de Puesto',
                'verbose_name_plural': 'Horarios de Puestos',
                'unique_together': {('puesto', 'dia')},
            },
        ),
    ]
