# Generated by Django 5.2.1 on 2026-02-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0024_puestohorario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='horas_trabajo',
        ),
    ]
