# Generated by Django 5.2.1 on 2026-02-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0025_remove_puesto_dias_remove_puesto_horas_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestohorario',
            name='turno',
            field=models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], default='Diurno', max_length=10),
        ),
    ]
