# Generated by Django 5.2.1 on 2026-02-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0026_puestohorario_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='turno',
        ),
        migrations.AlterField(
            model_name='puestohorario',
            name='horas',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
