# Generated by Django 5.2.1 on 2026-02-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0027_remove_puesto_turno_alter_puestohorario_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='cantidad_guardias',
            field=models.IntegerField(default=1),
        ),
    ]
