# Generated by Django 5.2.1 on 2026-02-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0028_alter_puesto_cantidad_guardias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestohorario',
            name='turno',
            field=models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno'), ('Ambos', 'Ambos')], default='Diurno', max_length=10),
        ),
    ]
