# Generated by Django 5.2.1 on 2026-02-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0029_alter_puestohorario_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('FIJO', 'FIJO'), ('SACAFRANCO', 'SACAFRANCO'), ('EVENTUAL', 'EVENTUAL')], max_length=15, null=True),
        ),
    ]
