# Generated by Django 5.2.1 on 2026-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0030_alter_persona_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('FIJOS', 'FIJOS'), ('RETENES', 'RETENES'), ('EVENTUALES', 'EVENTUALES'), ('SACAFRANCO', 'SACAFRANCO'), ('SACAVACACIONES', 'SACAVACACIONES'), ('SUPERVISOR ZONAL', 'SUPERVISOR ZONAL'), ('SUPERVISOR MOTORIZADO', 'SUPERVISOR MOTORIZADO')], max_length=25, null=True),
        ),
    ]
