# Generated by Django 5.2.1 on 2026-02-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0031_alter_persona_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='size',
            field=models.CharField(choices=[('PEQUENO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], db_index=True, default='MEDIANO', max_length=10, verbose_name='Tamaño del Cliente'),
        ),
    ]
