# Generated by Django 5.2.1 on 2026-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0032_cliente_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='size',
            field=models.CharField(choices=[('PEQUENO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande'), ('OFICINA', 'Oficina')], db_index=True, default='MEDIANO', max_length=10, verbose_name='Tamaño del Cliente'),
        ),
    ]
