# Generated by Django 5.2.1 on 2026-02-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0033_alter_cliente_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
