# Generated by Django 5.2.1 on 2026-02-20 16:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0034_puesto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Use 3 o 4 dígitos', regex='^\\d{3,4}$')])),
                ('secuencia', models.JSONField(help_text='Ciclo ordenado (D/N/F/-)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='patronHorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='CoreFisica.patronhorario'),
        ),
    ]
