# Generated by Django 5.2.1 on 2026-02-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0035_patronhorario_horario_patronhorario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatronHorario',
            new_name='PatronAsignacion',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='patronHorario',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='patronAsignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='CoreFisica.patronasignacion'),
        ),
    ]
