# Generated by Django 5.2.1 on 2026-02-23 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0036_rename_patronhorario_patronasignacion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacionsemanal',
            unique_together={('puesto', 'week_start')},
        ),
        migrations.AddField(
            model_name='asignacionsemanal',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semanales', to='CoreFisica.asignacion'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionsemanal',
            unique_together={('asignacion', 'week_start'), ('puesto', 'week_start')},
        ),
    ]
