# Generated by Django 5.2.1 on 2026-03-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0037_alter_asignacionsemanal_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'ordering': ['provincia', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='instalacion',
            name='provincia',
        ),
        migrations.AddField(
            model_name='instalacion',
            name='canton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='CoreFisica.canton'),
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cantones', to='CoreFisica.provincia'),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='CoreFisica.instalacion')),
            ],
            options={
                'ordering': ['instalacion', 'orden', 'codigo'],
                'unique_together': {('codigo', 'instalacion')},
            },
        ),
        migrations.AddField(
            model_name='puesto',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='CoreFisica.zona'),
        ),
        migrations.AlterUniqueTogether(
            name='canton',
            unique_together={('provincia', 'nombre')},
        ),
    ]
