# Generated by Django 5.2.1 on 2026-03-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0038_canton_provincia_remove_instalacion_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacion',
            name='ciudad',
        ),
    ]
