# Generated by Django 5.2.1 on 2026-03-03 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0039_remove_instalacion_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='CoreFisica.provincia'),
        ),
    ]
