# Generated by Django 5.2.1 on 2026-03-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0041_remove_zona_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='orden',
        ),
    ]
