# Generated by Django 5.2.1 on 2026-03-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0042_remove_zona_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['instalacion', 'codigo']},
        ),
    ]
