# Generated by Django 5.2.1 on 2026-03-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0043_alter_zona_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zona',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='zona',
            name='codigo',
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['instalacion', 'titulo']},
        ),
    ]
