# Generated by Django 5.2.1 on 2026-03-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0044_remove_zona_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
