# Generated by Django 5.2.1 on 2026-03-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0045_instalacion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='titulo',
            field=models.CharField(choices=[('Zona 1', 'Zona 1'), ('Zona 2', 'Zona 2'), ('Zona 3', 'Zona 3')], db_index=True, max_length=100),
        ),
    ]
