# Generated by Django 5.2.1 on 2026-03-04 22:19

import CoreFisica.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0046_alter_zona_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='anio',
            field=models.PositiveSmallIntegerField(default=CoreFisica.models.current_year),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='mes',
            field=models.PositiveSmallIntegerField(default=CoreFisica.models.current_month),
        ),
        migrations.CreateModel(
            name='ReporteAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('puesto_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('TURNO', 'Turno'), ('ADICIONAL', 'Adicional')], default='TURNO', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asistencia', to='CoreFisica.cliente')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asistencia', to='CoreFisica.horario')),
                ('instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asistencia', to='CoreFisica.instalacion')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asistencia', to='CoreFisica.persona')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asistencia', to='CoreFisica.puesto')),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['fecha'], name='CoreFisica__fecha_07d5d0_idx'), models.Index(fields=['estado'], name='CoreFisica__estado_ee4174_idx')],
            },
        ),
    ]
