# Generated by Django 5.2.1 on 2026-03-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0047_alter_asignacion_anio_alter_asignacion_mes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteasistencia',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='reporteasistencia',
            name='CoreFisica__fecha_07d5d0_idx',
        ),
        migrations.RemoveField(
            model_name='reporteasistencia',
            name='fecha',
        ),
    ]
