# Generated by Django 5.2.1 on 2026-03-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0048_alter_reporteasistencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteasistencia',
            name='asignacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporte_asistencia', to='CoreFisica.asignacion'),
        ),
        migrations.AlterField(
            model_name='reporteasistencia',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
