# Generated by Django 5.2.1 on 2026-03-06 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0049_reporteasistencia_asignacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteasistencia',
            name='modificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteasistencia',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asistencia_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporteasistencia',
            name='estado',
            field=models.CharField(choices=[('TURNO', 'Turno'), ('ADICIONAL', 'Adicional'), ('EVENTUAL', 'Eventual'), ('ADEL/TURNO', 'Adel/Turno')], default='TURNO', max_length=12),
        ),
    ]
