# Generated by Django 5.2.1 on 2026-03-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0050_reporteasistencia_modificado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteasistencia',
            name='reemplazo',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['SACAFRANCO', 'RETENES', 'SACAVACACIONES', 'EVENTUALES', 'SUPERVISOR ZONAL', 'SUPERVISOR MOTORIZADO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_como_reemplazo', to='CoreFisica.persona'),
        ),
    ]
