# Generated by Django 5.2.1 on 2026-03-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0052_alter_asignacionsemanal_unique_together_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteasistencia',
            name='row_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='reporteasistencia',
            name='reemplazo',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['FIJOS', 'SACAFRANCO', 'RETENES', 'SACAVACACIONES', 'EVENTUALES', 'SUPERVISOR ZONAL', 'SUPERVISOR MOTORIZADO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_como_reemplazo', to='CoreFisica.persona'),
        ),
    ]
