# Generated by Django 5.2.1 on 2026-03-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0053_reporteasistencia_row_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacionsemanal',
            unique_together={('asignacion', 'week_start')},
        ),
        migrations.AddIndex(
            model_name='asignacionsemanal',
            index=models.Index(fields=['asignacion', 'week_start'], name='CoreFisica__asignac_55cc99_idx'),
        ),
    ]
