# Generated by Django 5.2.1 on 2026-03-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0054_alter_asignacionsemanal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_ingreso',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_retiro',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
