# Generated by Django 4.x on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0058_remove_cliente_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='agregar_sacafranco',
            field=models.BooleanField(default=False),
        ),
    ]
