# Generated by Django 4.x on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0059_asignacion_agregar_sacafranco'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='sacafranco_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='sacafranco_miembros', to='CoreFisica.asignacion'),
        ),
    ]
