# Generated by Django 4.x on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0060_asignacion_sacafranco_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
