# Generated by Django 5.2.1 on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models
import CoreFisica.models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0061_asignacion_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='SacafrancoFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(default=CoreFisica.models.current_month)),
                ('anio', models.PositiveSmallIntegerField(default=CoreFisica.models.current_year)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='sacafranco_fila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='CoreFisica.sacafrancofila'),
        ),
        migrations.AddIndex(
            model_name='sacafrancofila',
            index=models.Index(fields=['mes', 'anio'], name='CoreFisica_sacafranco_fila_mes_anio_idx'),
        ),
    ]
