# Generated by Django 5.2.1 on 2026-03-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0062_sacafranco_fila_free'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "CoreFisica_sacafranco_fila_mes_anio_idx" RENAME TO "CoreFisica__mes_97eea9_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "CoreFisica__mes_97eea9_idx" RENAME TO "CoreFisica_sacafranco_fila_mes_anio_idx";'
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='sacafrancofila',
                    new_name='CoreFisica__mes_97eea9_idx',
                    old_name='CoreFisica_sacafranco_fila_mes_anio_idx',
                ),
            ],
        ),
    ]
