# Generated by Django 5.2.1 on 2026-03-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0063_rename_corefisica_sacafranco_fila_mes_anio_idx_corefisica__mes_97eea9_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SacafrancoFilaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('mon', models.CharField(blank=True, max_length=16)),
                ('tue', models.CharField(blank=True, max_length=16)),
                ('wed', models.CharField(blank=True, max_length=16)),
                ('thu', models.CharField(blank=True, max_length=16)),
                ('fri', models.CharField(blank=True, max_length=16)),
                ('sat', models.CharField(blank=True, max_length=16)),
                ('sun', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sacafranco_fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanales', to='CoreFisica.sacafrancofila')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sacafrancofilasemanal',
            unique_together={('sacafranco_fila', 'week_start')},
        ),
        migrations.AddIndex(
            model_name='sacafrancofilasemanal',
            index=models.Index(fields=['week_start'], name='CoreFisica_sacafranco_fila_semanal_week_start_idx'),
        ),
        migrations.AddIndex(
            model_name='sacafrancofilasemanal',
            index=models.Index(fields=['sacafranco_fila', 'week_start'], name='CoreFisica_sacafranco_fila_semanal_fila_week_idx'),
        ),
    ]
