# Generated by Django 5.2.1 on 2026-03-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0064_sacafranco_fila_semanal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sacafrancofilasemanal',
            new_name='CoreFisica__week_st_373e58_idx',
            old_name='CoreFisica_sacafranco_fila_semanal_week_start_idx',
        ),
        migrations.RenameIndex(
            model_name='sacafrancofilasemanal',
            new_name='CoreFisica__sacafra_55232b_idx',
            old_name='CoreFisica_sacafranco_fila_semanal_fila_week_idx',
        ),
    ]
