# Generated by Django 5.2.1 on 2026-03-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0066_patronasignacion_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patronasignacion',
            name='start_date',
        ),
    ]
