# Generated by Django 5.2.1 on 2026-03-30 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0068_remove_asignacion_sacafranco_fila'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacafrancofila',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoreFisica.persona'),
        ),
    ]
