# Generated by Django 5.2.1 on 2026-03-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0069_sacafrancofila_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteasistencia',
            name='fecha_reporte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
