# Generated by Django 5.2.1 on 2026-03-30 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0070_reporteasistencia_fecha_reporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAsistenciaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=12, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('row_color', models.CharField(blank=True, max_length=7, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asistencia', to='CoreFisica.asignacion')),
                ('reemplazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoreFisica.persona')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='CoreFisica.reporteasistencia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['asignacion', 'fecha_reporte'], name='CoreFisica__asignac_856744_idx')],
            },
        ),
    ]
