# Generated by Django 5.2.1 on 2026-03-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0071_reporteasistenciahistorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteasistencia',
            name='estado',
            field=models.CharField(choices=[('TURNO', 'Turno'), ('ADICIONAL', 'Adicional'), ('EVENTUAL', 'Eventual'), ('ADEL/TURNO', 'Adel/Turno'), ('DOBLADO', 'Doblado'), ('FR/TRABAJADO', 'Fr/Trabajado'), ('RETEN', 'Reten'), ('CUSTODIO', 'Custodio')], default='TURNO', max_length=12),
        ),
    ]
