# Generated by Django 5.2.1 on 2026-03-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0072_alter_reporteasistencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
