# Generated by Django 5.2.1 on 2026-03-31 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0073_cliente_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigo',
        ),
    ]
