# Generated by Django 5.2.1 on 2026-04-01 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0074_remove_cliente_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalConsola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('turno', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], db_index=True, max_length=10)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Cédula: sólo dígitos, máximo 10', regex='^\\d{1,10}$')])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('OPERADOR', 'Operador'), ('OCEAN SECURITY', 'Ocean Security')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['fecha', 'turno'], name='CoreFisica__fecha_a68138_idx')],
            },
        ),
    ]
