# Generated by Django 5.2.1 on 2026-04-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0075_personalconsola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('turno', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], db_index=True, max_length=10)),
                ('tipo', models.CharField(choices=[('CONSOLa', 'Consola'), ('GUARDIA', 'Guardia')], db_index=True, max_length=10)),
                ('referencia_id', models.PositiveIntegerField(db_index=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha', 'turno', 'tipo', 'referencia_id'],
                'indexes': [models.Index(fields=['fecha', 'turno', 'tipo'], name='CoreFisica__fecha_54f286_idx'), models.Index(fields=['tipo', 'referencia_id'], name='CoreFisica__tipo_4d4b88_idx')],
            },
        ),
    ]
