# Generated by Django 5.2.1 on 2026-04-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0076_consolidado'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='personalconsola',
            name='CoreFisica__fecha_a68138_idx',
        ),
        migrations.RemoveField(
            model_name='personalconsola',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='personalconsola',
            name='fecha',
        ),
    ]
