# Generated by Django 5.2.1 on 2026-04-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0077_remove_personalconsola_corefisica__fecha_a68138_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalconsola',
            name='tipo',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('OPERADOR', 'Operador'), ('OCEAN SECURITY', 'Ocean Security')], default='OPERADOR', max_length=20),
        ),
    ]
