# Generated by Django 5.2.1 on 2026-04-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0078_personalconsola_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidado',
            name='nominativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consolidado',
            name='proyecto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
