# Generated by Django 5.2.1 on 2026-04-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0079_consolidado_nominativo_consolidado_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('turno', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], db_index=True, max_length=10)),
                ('faltas', models.PositiveIntegerField(default=0)),
                ('huecas', models.PositiveIntegerField(default=0)),
                ('apoyos', models.PositiveIntegerField(default=0)),
                ('capacitacion', models.PositiveIntegerField(default=0)),
                ('apertura_puesto', models.PositiveIntegerField(default=0)),
                ('servicios_temporales', models.PositiveIntegerField(default=0)),
                ('servicios_adicionales', models.PositiveIntegerField(default=0)),
                ('aprendiendo_consignas', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'turno'], name='CoreFisica__fecha_074e2c_idx')],
                'unique_together': {('fecha', 'turno')},
            },
        ),
    ]
