# Generated by Django 5.2.1 on 2026-04-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0080_consolidadoresumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='cedula_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
