# Generated by Django 5.2.1 on 2026-04-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0082_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
