# Generated by Django 5.2.1 on 2026-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0083_userprofile_cargo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'permissions': [('export_asignacion', 'Can export asignacion')]},
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('FIJOS', 'FIJOS'), ('RETENES', 'RETENES'), ('CUSTODIO', 'CUSTODIO'), ('EVENTUALES', 'EVENTUALES'), ('SACAFRANCO', 'SACAFRANCO'), ('SACAVACACIONES', 'SACAVACACIONES'), ('SUPERVISOR ZONAL', 'SUPERVISOR ZONAL'), ('SUPERVISOR MOTORIZADO', 'SUPERVISOR MOTORIZADO')], max_length=25, null=True),
        ),
    ]
