# Generated by Django 5.2.1 on 2026-04-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0084_alter_asignacion_options_alter_persona_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('import_cliente', 'Can import cliente')]},
        ),
    ]
