# Generated by Django 5.2.1 on 2026-04-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0085_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteasistencia',
            options={'ordering': ['-created_at'], 'permissions': [('export_reporte_asistencia', 'Can export reporte asistencia')]},
        ),
    ]
