# Generated by Django 5.2.1 on 2026-04-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0086_alter_reporteasistencia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consolidado',
            options={'ordering': ['fecha', 'turno', 'tipo', 'referencia_id'], 'permissions': [('export_consolidado', 'Can export consolidado')]},
        ),
    ]
