# Generated by Django 5.2.1 on 2026-04-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0087_alter_consolidado_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puesto',
            old_name='cantidad_guardias',
            new_name='cantidad_puestos',
        ),
    ]
