# Generated by Django 5.2.1 on 2026-04-22 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0088_rename_cantidad_guardias_puesto_cantidad_puestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='canton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CoreFisica.canton'),
        ),
        migrations.AddField(
            model_name='persona',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CoreFisica.provincia'),
        ),
    ]
