# Generated by Django 5.2.1 on 2026-04-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0089_persona_canton_persona_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoberturaSacafranco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('day', models.CharField(choices=[('mon', 'Lunes'), ('tue', 'Martes'), ('wed', 'Miércoles'), ('thu', 'Jueves'), ('fri', 'Viernes'), ('sat', 'Sábado'), ('sun', 'Domingo')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas_sacafranco', to='CoreFisica.persona')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas_sacafranco', to='CoreFisica.puesto')),
            ],
            options={
                'unique_together': {('persona', 'week_start', 'day'), ('puesto', 'week_start', 'day')},
                'indexes': [models.Index(fields=['week_start'], name='CoreFisica__week_st_9c6553_idx'), models.Index(fields=['puesto', 'week_start', 'day'], name='CoreFisica__puesto__4284ec_idx'), models.Index(fields=['persona', 'week_start', 'day'], name='CoreFisica__persona_b7af91_idx')],
            },
        ),
    ]