# Generated by Django 5.2.1 on 2026-04-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0090_coberturasacafranco'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coberturasacafranco',
            new_name='CoreFisica__week_st_c9ae3b_idx',
            old_name='CoreFisica__week_st_9c6553_idx',
        ),
        migrations.RenameIndex(
            model_name='coberturasacafranco',
            new_name='CoreFisica__puesto__02daf6_idx',
            old_name='CoreFisica__puesto__4284ec_idx',
        ),
        migrations.RenameIndex(
            model_name='coberturasacafranco',
            new_name='CoreFisica__persona_babf8c_idx',
            old_name='CoreFisica__persona_b7af91_idx',
        ),
    ]
