# Generated by Django 5.2.1 on 2026-04-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0091_rename_corefisica__week_st_9c6553_idx_corefisica__week_st_c9ae3b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'permissions': [('export_asignacion', 'Can export asignacion'), ('import_puestos_asignaciones', 'Can import puestos/asignaciones')]},
        ),
    ]
