# Generated by Django 5.2.1 on 2026-05-04 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0093_asignacion_publicada_calendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('FIJOS', 'FIJOS'), ('RETENES', 'RETENES'), ('CUSTODIO', 'CUSTODIO'), ('EVENTUALES', 'EVENTUALES'), ('SACAFRANCO', 'SACAFRANCO'), ('SACAVACACIONES', 'SACAVACACIONES'), ('SUPERVISOR ZONAL', 'SUPERVISOR ZONAL'), ('SUPERVISOR MOTORIZADO', 'SUPERVISOR MOTORIZADO'), ('SUPERVISOR DE ACOMPAÑAMIENTO', 'SUPERVISOR DE ACOMPAÑAMIENTO')], max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='reporteasistencia',
            name='reemplazo',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['FIJOS', 'SACAFRANCO', 'RETENES', 'SACAVACACIONES', 'EVENTUALES', 'SUPERVISOR ZONAL', 'SUPERVISOR MOTORIZADO', 'SUPERVISOR DE ACOMPAÑAMIENTO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_como_reemplazo', to='CoreFisica.persona'),
        ),
    ]
