# Generated by Django 5.2.1 on 2026-05-05 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0094_alter_persona_tipo_alter_reporteasistencia_reemplazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacafrancofila',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CoreFisica.provincia'),
        ),
    ]
