# Generated by Django 5.2.1 on 2026-05-12 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0095_sacafrancofila_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronasignacion',
            name='codigo',
            field=models.CharField(db_index=True, max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Use 2 a 4 dígitos', regex='^\\d{2,4}$')]),
        ),
    ]
