# Generated by Django 5.2.1 on 2026-05-15 00:00

import django.db.models.deletion
from django.db import migrations, models


def forwards_reten(apps, schema_editor):
    Persona = apps.get_model('CoreFisica', 'Persona')
    Persona.objects.filter(tipo='RETENES').update(tipo='RETEN')


def backwards_reten(apps, schema_editor):
    Persona = apps.get_model('CoreFisica', 'Persona')
    Persona.objects.filter(tipo='RETEN').update(tipo='RETENES')


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0096_alter_patronasignacion_codigo'),
    ]

    operations = [
        migrations.RunPython(forwards_reten, backwards_reten),
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('FIJOS', 'FIJOS'),
                    ('RETEN', 'RETEN'),
                    ('CUSTODIO', 'CUSTODIO'),
                    ('EVENTUALES', 'EVENTUALES'),
                    ('SACAFRANCO', 'SACAFRANCO'),
                    ('SACAVACACIONES', 'SACAVACACIONES'),
                    ('SUPERVISOR ZONAL', 'SUPERVISOR ZONAL'),
                    ('SUPERVISOR MOTORIZADO', 'SUPERVISOR MOTORIZADO'),
                    ('SUPERVISOR DE ACOMPAÑAMIENTO', 'SUPERVISOR DE ACOMPAÑAMIENTO'),
                ],
                max_length=28,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reporteasistencia',
            name='reemplazo',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    'tipo__in': [
                        'FIJOS',
                        'SACAFRANCO',
                        'RETEN',
                        'SACAVACACIONES',
                        'EVENTUALES',
                        'SUPERVISOR ZONAL',
                        'SUPERVISOR MOTORIZADO',
                        'SUPERVISOR DE ACOMPAÑAMIENTO',
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reportes_como_reemplazo',
                to='CoreFisica.persona',
            ),
        ),
    ]
