# Generated by Django 5.2.1 on 2026-05-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0098_alter_persona_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteasistencia',
            name='reemplazo',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['FIJOS', 'SACAFRANCO', 'RETEN', 'SACAVACACIONES', 'EVENTUAL', 'SUPERVISOR ZONAL', 'SUPERVISOR MOTORIZADO', 'SUPERVISOR DE ACOMPAÑAMIENTO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_como_reemplazo', to='CoreFisica.persona'),
        ),
    ]
