# Generated by Django 5.2.1 on 2026-05-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0099_alter_reporteasistencia_reemplazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('FIJOS', 'FIJOS'), ('RETEN', 'RETEN'), ('CUSTODIO', 'CUSTODIO'), ('EVENTUAL', 'EVENTUAL'), ('SACAFRANCO', 'SACAFRANCO'), ('SACAVACACIONES', 'SACAVACACIONES'), ('SUPERVISOR ZONAL', 'SUPERVISOR ZONAL'), ('SUPERVISOR EVENTUAL', 'SUPERVISOR EVENTUAL'), ('SUPERVISOR MOTORIZADO', 'SUPERVISOR MOTORIZADO'), ('SUPERVISOR DE ACOMPAÑAMIENTO', 'SUPERVISOR DE ACOMPAÑAMIENTO')], max_length=28, null=True),
        ),
    ]
