# Generated by Django 5.2.1 on 2026-05-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0103_consolidado_explicit_refs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consolidado',
            options={'ordering': ['fecha', 'turno', 'tipo', 'id'], 'permissions': [('export_consolidado', 'Can export consolidado')]},
        ),
        migrations.RemoveConstraint(
            model_name='consolidado',
            name='corefisica_consolidado_consola_ref_ck',
        ),
        migrations.RemoveConstraint(
            model_name='consolidado',
            name='corefisica_consolidado_guardia_ref_ck',
        ),
        migrations.RemoveIndex(
            model_name='consolidado',
            name='CoreFisica__tipo_4d4b88_idx',
        ),
        migrations.RemoveField(
            model_name='consolidado',
            name='referencia_id',
        ),
        migrations.AddConstraint(
            model_name='consolidado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'CONSOLa'), _negated=True), ('asignacion_ref__isnull', True), _connector='OR'), name='corefisica_consolidado_consola_ref_ck'),
        ),
        migrations.AddConstraint(
            model_name='consolidado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'GUARDIA'), _negated=True), ('persona_ref__isnull', True), _connector='OR'), name='corefisica_consolidado_guardia_ref_ck'),
        ),
    ]
