# Generated by Django 5.2.1 on 2026-05-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0105_reporteasistencia_estado_asistencia'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reporteasistencia',
            new_name='CoreFisica__estado__0152f2_idx',
            old_name='CoreFisica__estado__22a55d_idx',
        ),
    ]
