# Generated by Django 5.2.1 on 2026-06-05 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0107_consolidado_provincia_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCalendarioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('dia', models.CharField(max_length=3)),
                ('valor_anterior', models.CharField(blank=True, max_length=10)),
                ('valor_nuevo', models.CharField(blank=True, max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_calendario', to='CoreFisica.asignacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['-creado_en'], name='CoreFisica__creado__78616e_idx'), models.Index(fields=['asignacion', 'week_start'], name='CoreFisica__asignac_44fa70_idx'), models.Index(fields=['usuario'], name='CoreFisica__usuario_8a241c_idx')],
            },
        ),
    ]
