# Generated by Django 5.2.1 on 2026-06-08 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0108_asignacioncalendariolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos', to='CoreFisica.horario'),
        ),
    ]
