# Generated by Django 5.2.1 on 2026-06-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0110_backfill_puesto_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoreFisica.persona'),
        ),
    ]
