# Generated by Django 5.2.1 on 2026-06-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0117_unaccent_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaCanton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantones', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
