# Generated by Django 5.2.1 on 2026-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0118_vistacanton'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistacanton',
            name='clientes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vistacanton',
            name='tipo',
            field=models.CharField(choices=[('canton', 'Cantones'), ('cliente', 'Empresas')], default='canton', max_length=10),
        ),
    ]
