# Generated by Django 5.2.1 on 2026-06-12 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0120_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacafrancofila',
            name='cantones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='sacafrancofila',
            name='clientes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
