# Generated by Django 5.2.1 on 2026-06-15 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0121_sacafrancofila_cantones_sacafrancofila_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='sector',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='NovedadPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], default='Diurno', max_length=10)),
                ('cliente_denominativo', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=150)),
                ('novedad', models.CharField(choices=[('APERTURA', 'Apertura'), ('MODIFICACION', 'Modificación'), ('CIERRE', 'Cierre'), ('INCREMENTO', 'Incremento'), ('MODIFICACION INCREMENTO', 'Modificación / Incremento')], max_length=40)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('horario', models.CharField(blank=True, max_length=100)),
                ('solicitado_por', models.CharField(blank=True, max_length=150)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='CoreFisica.instalacion')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='CoreFisica.puesto')),
            ],
            options={
                'ordering': ['-fecha', 'turno', 'cliente_denominativo'],
                'permissions': [('export_novedadpuesto', 'Puede exportar reporte de novedades de puesto')],
                'indexes': [models.Index(fields=['fecha'], name='CoreFisica__fecha_b5bda8_idx'), models.Index(fields=['fecha', 'turno'], name='CoreFisica__fecha_393567_idx')],
            },
        ),
    ]
