# Generated by Django 5.2.1 on 2026-06-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0122_instalacion_sector_novedadpuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
    ]
