# Generated by Django 5.2.1 on 2026-06-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0123_puesto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistacanton',
            name='tipos',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vistacanton',
            name='tipo',
            field=models.CharField(choices=[('canton', 'Cantones'), ('cliente', 'Empresas'), ('persona_tipo', 'Tipos de persona')], default='canton', max_length=20),
        ),
    ]
