# Generated by Django 5.2.1 on 2026-06-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0124_vistacanton_tipos_alter_vistacanton_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacafrancofila',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sacafrancofila',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
