# Generated by Django 5.2.1 on 2026-06-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0125_sacafrancofila_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestohorario',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=4),
        ),
    ]
