# Generated by Django 5.2.1 on 2026-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0126_alter_puestohorario_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestohorario',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puestohorario',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
