# Generated by Django 5.2.1 on 2026-06-18 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0128_puestos_cantidad_uno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoreFisica.horario'),
        ),
    ]
