# Generated by Django 5.2.1 on 2026-06-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0129_alter_asignacion_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistacanton',
            name='instalaciones',
            field=models.JSONField(default=list),
        ),
    ]
