# Generated by Django 5.2.1 on 2026-06-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0131_persona_cargo_persona_correo_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='actividad',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='persona',
            name='affis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='centro_costo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='persona',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='CoreFisica.cliente'),
        ),
        migrations.AddField(
            model_name='persona',
            name='codigo_erp',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='persona',
            name='conyuge',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_pago_liquidacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='forma_pago',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='personas/'),
        ),
        migrations.AddField(
            model_name='persona',
            name='gypaseg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='persona',
            name='motivo_salida',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='persona',
            name='numero_afiliacion',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='persona',
            name='numero_contrato',
            field=models.CharField(blank=30, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='persona',
            name='parroquia',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='persona',
            name='pbip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='perfil',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='persona',
            name='region',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_empleado',
            field=models.CharField(blank=True, choices=[('EMPLEADO', 'Empleado'), ('OPERADOR', 'Operador'), ('OBRERO', 'Obrero')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='unidad_negocio',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], default='', max_length=10),
        ),
    ]
