# Generated by Django 5.2.1 on 2026-06-24 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0132_persona_actividad_persona_affis_persona_centro_costo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoNomina',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nomina', serialize=False, to='CoreFisica.persona')),
                ('sueldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desc_genesis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonificacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compensacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('horas_25', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('horas_50', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('horas_100', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pagar_fondo_reserva', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('decimo_tercer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('decimo_cuarto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vacaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fondo_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pagar_rol_10mo_3ero', models.BooleanField(default=False)),
                ('pagar_rol_10mo_4to', models.BooleanField(default=False)),
                ('pagar_rol_vacaciones', models.BooleanField(default=False)),
                ('desc_aporte_conyuge', models.BooleanField(default=False)),
                ('giro_contable_liquidacion', models.BooleanField(default=False)),
                ('numero_liquidacion_ministerio', models.CharField(blank=True, default='', max_length=60)),
                ('moviliza', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lunch', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anticipo_22', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('viaticos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_extra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('concepto', models.CharField(blank=True, default='', max_length=255)),
                ('subsidio_enfermedad', models.BooleanField(default=False)),
                ('subsidio_enfermedad_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subsidio_accidente', models.BooleanField(default=False)),
                ('subsidio_accidente_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subsidio_maternidad', models.BooleanField(default=False)),
                ('subsidio_maternidad_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
