# Generated by Django 5.2.1 on 2026-06-24 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0133_empleadonomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoOtrosDatos',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='otros_datos', serialize=False, to='CoreFisica.persona')),
                ('incluir_en_rol', models.BooleanField(default=True)),
                ('acreditar', models.BooleanField(default=False)),
                ('ultima_liquidacion', models.DateField(blank=True, null=True)),
                ('grupo_sanguineo', models.CharField(blank=True, default='', max_length=8)),
                ('banco', models.CharField(blank=True, default='', max_length=80)),
                ('cuenta_ahorros', models.CharField(blank=True, default='', max_length=30)),
                ('cuenta_corriente', models.CharField(blank=True, default='', max_length=30)),
                ('fecha_ini_vacaciones', models.DateField(blank=True, null=True)),
                ('fecha_fin_vacaciones', models.DateField(blank=True, null=True)),
                ('dias_vacaciones', models.IntegerField(default=0)),
                ('codigo_cuenta', models.CharField(blank=True, default='', max_length=30)),
                ('cuenta_departamento', models.CharField(blank=True, default='', max_length=20)),
                ('cuenta_auxiliar', models.CharField(blank=True, default='', max_length=30)),
                ('numero_cargas', models.IntegerField(default=0)),
                ('gasto_salud', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_vestimenta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_educacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_vivienda', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_alimentacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_arte_cultura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_turismo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
