# Generated by Django 5.2.1 on 2026-06-24 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0134_empleadootrosdatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoReferencias',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='referencias', serialize=False, to='CoreFisica.persona')),
                ('cedula_militar', models.CharField(blank=True, default='', max_length=30)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('maniobras', models.CharField(blank=True, default='', max_length=120)),
                ('carnet_conadis', models.CharField(blank=True, default='', max_length=40)),
                ('numero_certificado_votacion', models.CharField(blank=True, default='', max_length=40)),
                ('licencia_conducir', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_iess', models.CharField(blank=True, default='', max_length=40)),
                ('certificado_violencia_intrafamiliar', models.CharField(blank=True, default='', max_length=120)),
                ('primaria', models.BooleanField(default=False)),
                ('secundaria', models.BooleanField(default=False)),
                ('universidad', models.BooleanField(default=False)),
                ('titulo', models.CharField(blank=True, default='', max_length=120)),
                ('anios_estudio', models.IntegerField(default=0)),
                ('miembro_fuerza_publica', models.BooleanField(default=False)),
                ('realizo_servicio_militar', models.BooleanField(default=False)),
                ('contrato_inspectoria', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
