# Generated by Django 5.2.1 on 2026-06-24 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0135_empleadoreferencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='PDF GENERAL', max_length=60)),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=255)),
                ('ruta_archivo', models.CharField(blank=True, default='', max_length=500)),
                ('extension', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='CoreFisica.persona')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
