# Generated by Django 5.2.1 on 2026-06-24 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0136_empleadodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, default='', max_length=150)),
                ('puesto_cargo', models.CharField(blank=True, default='', max_length=150)),
                ('tiempo', models.CharField(blank=True, default='', max_length=60)),
                ('motivo_salida', models.CharField(blank=True, default='', max_length=150)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='CoreFisica.persona')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_capacitacion', models.CharField(blank=True, default='', max_length=150)),
                ('curso', models.CharField(blank=True, default='', max_length=150)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('horas', models.IntegerField(default=0)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones', to='CoreFisica.persona')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoNivelEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_estudio', models.CharField(blank=True, default='', max_length=80)),
                ('completa', models.BooleanField(default=False)),
                ('centro_capacitacion', models.CharField(blank=True, default='', max_length=150)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_estudio', to='CoreFisica.persona')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoReferenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_contactar', models.CharField(blank=True, default='', max_length=150)),
                ('relacion', models.CharField(blank=True, default='', max_length=60)),
                ('telefonos', models.CharField(blank=True, default='', max_length=80)),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_personales', to='CoreFisica.persona')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
