# Generated by Django 5.2.1 on 2026-06-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0137_empleadoexperiencia_empleadoformacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('grupo', models.CharField(blank=True, default='', max_length=40)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene', models.BooleanField(default=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='CoreFisica.persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='CoreFisica.tipocertificado')),
            ],
            options={
                'unique_together': {('persona', 'tipo')},
            },
        ),
    ]
