# Generated by Django 5.2.1 on 2026-06-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0138_tipocertificado_empleadocertificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadocertificado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
