# Generated by Django 5.2.1 on 2026-06-26 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0139_empleadocertificado_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='canton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='CoreFisica.canton'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cod_agrupacion',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cod_area',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cod_rol',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_erp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='control_cupo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='controla_factura_reverso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='copia_correo_1',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='copia_correo_2',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='copia_correo_3',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='copia_correo_4',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='copia_correo_5',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuenta_contable',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cupo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='cliente',
            name='desc_vta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_comercial',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_adicional',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_pago',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origen_ingreso',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='cliente',
            name='paga_iva',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='parroquia',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='plazo_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='CoreFisica.provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rep_legal',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='requiere_correo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('JURIDICA', 'Jurídica'), ('NATURAL', 'Natural')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_id',
            field=models.CharField(blank=True, choices=[('RUC', 'Registro Único de Contribuyente'), ('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_precio',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_venta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_puesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valoracion_custodias',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
