# Generated by Django 5.2.1 on 2026-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0140_cliente_canton_cliente_ciudad_cliente_cod_agrupacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('Mensual', 'Mensual'), ('Quincenal', 'Quincenal'), ('Semanal', 'Semanal')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='motivo_salida',
            field=models.CharField(blank=True, choices=[('Renuncia Voluntaria', 'Renuncia Voluntaria'), ('Despido', 'Despido'), ('Visto Bueno', 'Visto Bueno'), ('Terminación de Contrato', 'Terminación de Contrato'), ('Problemas Familiares', 'Problemas Familiares'), ('Mejor Propuesta de Trabajo', 'Mejor Propuesta de Trabajo')], default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='persona',
            name='perfil',
            field=models.CharField(blank=True, choices=[('SENSIBLE', 'Sensible'), ('RIGIDO', 'Rígido'), ('INDUSTRIAL', 'Industrial'), ('CUSTODIA', 'Custodia'), ('OTROS', 'Otros')], default='', max_length=60),
        ),
    ]
