# Generated by Django 5.2.1 on 2026-06-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0141_alter_persona_forma_pago_alter_persona_motivo_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('UNION LIBRE', 'Unión Libre'), ('VIUDO', 'Viudo')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('UNION LIBRE', 'Unión Libre'), ('VIUDO', 'Viudo')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Mensual'), ('QUINCENAL', 'Quincenal'), ('SEMANAL', 'Semanal')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='motivo_salida',
            field=models.CharField(blank=True, choices=[('RENUNCIA VOLUNTARIA', 'Renuncia Voluntaria'), ('DESPIDO', 'Despido'), ('VISTO BUENO', 'Visto Bueno'), ('TERMINACIÓN DE CONTRATO', 'Terminación de Contrato'), ('PROBLEMAS FAMILIARES', 'Problemas Familiares'), ('MEJOR PROPUESTA DE TRABAJO', 'Mejor Propuesta de Trabajo')], default='', max_length=120),
        ),
    ]
