# Generated by Django 5.2.1 on 2026-06-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0142_alter_cliente_estado_civil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('ECUATORIANA', 'Ecuatoriana'), ('EXTRANJERO', 'Extranjero'), ('OTROS', 'Otros')], default='', max_length=40),
        ),
    ]
