# Generated by Django 5.2.1 on 2026-06-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0143_remove_cliente_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[('Ecuatoriana', 'Ecuatoriana'), ('Extranjero', 'Extranjero'), ('Otros', 'Otros')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_empleado',
            field=models.CharField(blank=True, choices=[('EMPLEADO', 'Empleado'), ('OPERADOR', 'Operador'), ('OBRERO', 'Obrero o Eventual')], default='', max_length=20),
        ),
    ]
