# Generated by Django 5.2.1 on 2026-06-29 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0144_alter_persona_nacionalidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=120)),
                ('codigo', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='CoreFisica.canton')),
            ],
            options={
                'ordering': ['canton', 'nombre'],
                'unique_together': {('canton', 'nombre')},
            },
        ),
    ]
