# Generated by Django 5.2.1 on 2026-06-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0146_corregir_guayaquil_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='zona',
            field=models.CharField(blank=True, choices=[('Seguridad Física', 'Seguridad Física'), ('Seguridad Electrónica', 'Seguridad Electrónica'), ('Seguridad de Carga', 'Seguridad de Carga')], default='', max_length=80),
        ),
    ]
