# Generated by Django 5.2.1 on 2026-06-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0147_alter_cliente_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='region',
            field=models.CharField(blank=True, choices=[('SIERRA', 'Sierra'), ('COSTA', 'Costa')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo',
            field=models.CharField(choices=[('FIJOS', 'Fijos'), ('RETEN', 'Retén'), ('CUSTODIO', 'Custodio'), ('EVENTUAL', 'Eventual'), ('SACAFRANCO', 'Sacafranco'), ('SACAVACACIONES', 'Sacavacaciones'), ('SUPERVISOR ZONAL', 'Supervisor Zonal'), ('SUPERVISOR EVENTUAL', 'Supervisor Eventual'), ('SUPERVISOR MOTORIZADO', 'Supervisor Motorizado'), ('SUPERVISOR DE ACOMPAÑAMIENTO', 'Supervisor de Acompañamiento'), ('OPERADOR CENTRO CONTROL', 'Operador Centro Control'), ('SUPERVISOR CENTRO CONTROL', 'Supervisor Centro Control')], max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='unidad_negocio',
            field=models.CharField(blank=True, choices=[('SEGURIDAD FISICA', 'Seguridad Física'), ('SEGURIDAD DE CARGA', 'Seguridad de Carga')], default='', max_length=60),
        ),
    ]
