# Generated by Django 5.2.1 on 2026-06-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0149_alter_persona_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado_empleado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('LIQUIDADO', 'Liquidado'), ('SUSPENDIDO', 'Suspendido')], db_index=True, default='ACTIVO', max_length=12),
        ),
    ]
