# Generated by Django 5.2.1 on 2026-06-30 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0151_backfill_estado_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('turno', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], db_index=True, max_length=10)),
                ('seccion', models.CharField(choices=[('DOBLADAS', 'Dobladas'), ('ADICIONALES', 'Adicionales'), ('ADELANTOS', 'Adelantos'), ('NO_CUBIERTOS', 'No cubiertos'), ('FALTOS', 'Faltos'), ('HUECA', 'Hueca'), ('APOYO', 'Apoyo')], db_index=True, max_length=15)),
                ('cliente', models.CharField(blank=True, default='', max_length=120)),
                ('puesto', models.CharField(blank=True, default='', max_length=160)),
                ('persona_nombre', models.CharField(blank=True, default='', max_length=160)),
                ('proviene', models.CharField(blank=True, default='', max_length=40)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo', models.CharField(blank=True, default='', max_length=40)),
                ('autorizacion', models.CharField(blank=True, default='', max_length=120)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporte_guardia', to='CoreFisica.persona')),
            ],
            options={
                'ordering': ['fecha', 'turno', 'seccion', 'orden', 'id'],
                'indexes': [models.Index(fields=['fecha', 'turno', 'seccion'], name='CoreFisica__fecha_5eeec4_idx')],
            },
        ),
    ]
