# Generated by Django 5.2.1 on 2026-06-30 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0152_reporteguardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteguardia',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporteguardia',
            name='reporte_asistencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporte_guardia', to='CoreFisica.reporteasistencia'),
        ),
    ]
