# Generated by Django 5.2.1 on 2026-07-06 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0154_reporteguardia_asignacion_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, default='', max_length=120)),
                ('persona_sale', models.CharField(blank=True, default='', max_length=160)),
                ('periodo', models.CharField(blank=True, default='', max_length=40)),
                ('sacavacaciones', models.CharField(blank=True, default='', max_length=160)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('dias', models.PositiveIntegerField(default=0)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona_sale_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_reporte', to='CoreFisica.persona')),
                ('sacavacaciones_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cubre_vacaciones', to='CoreFisica.persona')),
            ],
            options={
                'ordering': ['-fecha_desde', 'orden', 'id'],
            },
        ),
    ]
