# Generated by Django 5.2.1 on 2026-07-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0155_reportevacaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='modulos_ocultos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
