# Generated by Django 5.2.1 on 2026-07-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0156_userprofile_modulos_ocultos'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevacaciones',
            name='dias_pendientes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportevacaciones',
            name='fecha_desde_pendiente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportevacaciones',
            name='fecha_hasta_pendiente',
            field=models.DateField(blank=True, null=True),
        ),
    ]
