# Generated by Django 5.2.1 on 2026-07-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0161_normalizar_tipo_eventuales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteasistencia',
            name='estado',
            field=models.CharField(blank=True, choices=[('TURNO', 'Turno'), ('ADICIONAL', 'Adicional'), ('EVENTUAL', 'Eventual'), ('ADEL/TURNO', 'Adel/Turno'), ('DOBLADO', 'Doblado'), ('FR/TRABAJADO', 'Fr/Trabajado'), ('RETEN', 'Reten'), ('CUSTODIO', 'Custodio')], max_length=12, null=True),
        ),
    ]
