# Generated by Django 5.2.1 on 2026-08-03 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0162_alter_reporteasistencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='puestos_asignaciones', max_length=40)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('ok', 'Completado'), ('error', 'Error')], db_index=True, default='procesando', max_length=12)),
                ('resumen', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
