# Generated by Django 5.2.1 on 2026-08-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0163_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteasistencia',
            name='hueca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporteasistencia',
            name='hueca_motivo',
            field=models.CharField(blank=True, choices=[('HUECA POR MOVIMIENTO INTERNO', 'Hueca por movimiento interno'), ('HUECA POR SACAFRANCO', 'Hueca por sacafranco'), ('HUECA POR ADELANTO DE TURNO', 'Hueca por adelanto de turno'), ('HUECA POR UNIDAD FIJA', 'Hueca por unidad fija'), ('HUECA POR RENUNCIA', 'Hueca por renuncia')], default='', max_length=40),
        ),
    ]
