# Generated by Django 5.2.1 on 2026-08-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0164_reporteasistencia_hueca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('letra', models.CharField(max_length=3, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zona operativa',
                'verbose_name_plural': 'Zonas operativas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Nominativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('instalacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominativo', to='CoreFisica.instalacion')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominativos', to='CoreFisica.zonaoperativa')),
            ],
            options={
                'verbose_name': 'Nominativo',
                'verbose_name_plural': 'Nominativos',
                'ordering': ['zona', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('zona', 'numero'), name='uniq_nominativo_zona_numero')],
            },
        ),
    ]
