# Generated by Django 5.2.1 on 2026-08-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0165_zonaoperativa_nominativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominativo',
            options={'ordering': ['letra', 'numero'], 'verbose_name': 'Nominativo', 'verbose_name_plural': 'Nominativos'},
        ),
        migrations.RemoveConstraint(
            model_name='nominativo',
            name='uniq_nominativo_zona_numero',
        ),
        migrations.RemoveField(
            model_name='zonaoperativa',
            name='letra',
        ),
        migrations.AddField(
            model_name='nominativo',
            name='letra',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='nominativo',
            constraint=models.UniqueConstraint(fields=('letra', 'numero'), name='uniq_nominativo_letra_numero'),
        ),
    ]
