# Generated by Django 5.2.1 on 2026-08-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0166_alter_nominativo_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nominativo',
            name='uniq_nominativo_letra_numero',
        ),
    ]
