# Generated by Django 5.2.1 on 2026-08-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0167_remove_nominativo_uniq_nominativo_letra_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activa'),
        ),
    ]
