# Generated by Django 5.2.1 on 2026-08-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0168_instalacion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
