# Generated by Django 5.2.1 on 2026-08-17 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0169_puesto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominativo',
            name='zona_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CoreFisica.zonaoperativa'),
        ),
        migrations.AddField(
            model_name='zonaoperativa',
            name='es_agrupacion',
            field=models.BooleanField(default=False),
        ),
    ]
