# Generated by Django 5.2.1 on 2026-08-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0170_nominativo_zona_anterior_zonaoperativa_es_agrupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteasistenciahistorial',
            name='hueca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporteasistenciahistorial',
            name='hueca_motivo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
