# Generated by Django 5.2.1 on 2026-08-28 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0171_reporteasistenciahistorial_hueca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SacafrancoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado_asistencia', models.CharField(blank=True, default='', max_length=10)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sacafranco_fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='CoreFisica.sacafrancofila')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha'], name='CoreFisica__fecha_64c16b_idx')],
                'unique_together': {('sacafranco_fila', 'fecha')},
            },
        ),
    ]
