# Generated by Django 5.2.1 on 2026-08-28 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0172_sacafrancoasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacafrancoasistencia',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sacafrancoasistencia',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sacafrancoasistencia',
            name='hueca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sacafrancoasistencia',
            name='hueca_motivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sacafrancoasistencia',
            name='reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CoreFisica.persona'),
        ),
        migrations.AddField(
            model_name='sacafrancoasistencia',
            name='row_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
