# Generated by Django 5.2.1 on 2026-08-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0173_sacafrancoasistencia_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteguardia',
            name='sacafranco_fila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporte_guardia', to='CoreFisica.sacafrancofila'),
        ),
    ]
