# Generated by Django 5.2.1 on 2026-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0174_reporteguardia_sacafranco_fila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionsemanal',
            name='fri',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='asignacionsemanal',
            name='mon',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='asignacionsemanal',
            name='sat',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='asignacionsemanal',
            name='sun',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='asignacionsemanal',
            name='thu',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='asignacionsemanal',
            name='tue',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='asignacionsemanal',
            name='wed',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
