# Generated by Django 5.2.1 on 2026-09-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0175_alter_asignacionsemanal_fri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='es_hueca',
            field=models.BooleanField(default=False),
        ),
    ]
