# Generated by Django 5.2.1 on 2026-09-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0178_acotar_asignaciones_abiertas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puestohorario',
            unique_together={('puesto', 'dia', 'turno')},
        ),
    ]
