# Generated by Django 5.2.1 on 2026-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0180_backfill_horas_puesto_por_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('UNION LIBRE', 'Unión Libre'), ('VIUDO', 'Viudo'), ('OTROS', 'Otros')], default='', max_length=20),
        ),
    ]
