# Generated by Django 5.2.1 on 2026-09-09 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0181_alter_persona_estado_civil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='validado',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='reporteasistencia',
            name='reemplazo',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['FIJOS', 'SACAFRANCO', 'RETEN', 'SACAVACACIONES', 'EVENTUAL', 'SUPERVISOR ZONAL', 'SUPERVISOR MOTORIZADO', 'SUPERVISOR EVENTUAL', 'SUPERVISOR DE ACOMPAÑAMIENTO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_como_reemplazo', to='CoreFisica.persona'),
        ),
        migrations.CreateModel(
            name='NotificacionEventual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, default='', max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('resuelta', models.BooleanField(db_index=True, default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_eventual', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_validacion', to='CoreFisica.persona')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
    ]
