# Generated by Django 5.2.1 on 2026-09-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0182_persona_validado_alter_reporteasistencia_reemplazo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPersonaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField()),
                ('hasta', models.DateField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_persona', to='CoreFisica.asignacion')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CoreFisica.persona')),
            ],
            options={
                'ordering': ['asignacion_id', 'desde'],
                'indexes': [models.Index(fields=['asignacion', 'desde'], name='CoreFisica__asignac_f7412d_idx')],
            },
        ),
    ]
