# Generated by Django 5.2.1 on 2026-09-09 19:18

from django.db import migrations, models


def backfill_cuenta(apps, schema_editor):
    """Rellena numero_cuenta/tipo_cuenta desde los campos antiguos ahorros/corriente."""
    OtrosDatos = apps.get_model('CoreFisica', 'EmpleadoOtrosDatos')
    for od in OtrosDatos.objects.all().iterator():
        if od.numero_cuenta:
            continue
        if (od.cuenta_ahorros or '').strip():
            od.numero_cuenta = od.cuenta_ahorros.strip()
            od.tipo_cuenta = 'AHORROS'
            od.save(update_fields=['numero_cuenta', 'tipo_cuenta'])
        elif (od.cuenta_corriente or '').strip():
            od.numero_cuenta = od.cuenta_corriente.strip()
            od.tipo_cuenta = 'CORRIENTE'
            od.save(update_fields=['numero_cuenta', 'tipo_cuenta'])


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0183_asignacionpersonaperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadootrosdatos',
            name='numero_cuenta',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empleadootrosdatos',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente'), ('DIGITAL', 'Digital')], default='', max_length=12),
        ),
        migrations.RunPython(backfill_cuenta, migrations.RunPython.noop),
    ]
