# Generated by Django 5.2.1 on 2026-09-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0184_empleadootrosdatos_numero_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteasistencia',
            name='persona_cobertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_como_cobertura_hueca', to='CoreFisica.persona'),
        ),
        migrations.AddField(
            model_name='reporteasistenciahistorial',
            name='persona_cobertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cobertura_hueca', to='CoreFisica.persona'),
        ),
    ]
