# Generated by Django 5.2.1 on 2026-09-15 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0185_reporteasistencia_persona_cobertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevacaciones',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sacavacaciones_cobertura', to='CoreFisica.asignacion'),
        ),
        migrations.AddField(
            model_name='reportevacaciones',
            name='instalacion',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='reportevacaciones',
            name='puesto',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
