# Generated by Django 5.2.1 on 2026-09-16 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0186_reportevacaciones_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacafrancofila',
            name='vista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sacafrancos', to='CoreFisica.vistacanton'),
        ),
    ]
