# Generated by Django 5.2.1 on 2026-09-18 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0187_sacafrancofila_vista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SacafrancoAsistenciaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='', max_length=30)),
                ('estado_asistencia', models.CharField(blank=True, default='', max_length=10)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('row_color', models.CharField(blank=True, default='', max_length=20)),
                ('hueca', models.BooleanField(default=False)),
                ('hueca_motivo', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reemplazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CoreFisica.persona')),
                ('sacafranco_fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asistencia', to='CoreFisica.sacafrancofila')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['sacafranco_fila', 'fecha_reporte'], name='CoreFisica__sacafra_4239b3_idx')],
            },
        ),
    ]
