# Generated by Django 5.2.1 on 2026-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0188_sacafrancoasistenciahistorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteguardia',
            name='proviene',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
