# Generated by Django 5.2.1 on 2026-09-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0189_alter_reporteguardia_proviene'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='vigente_desde',
            field=models.DateField(blank=True, null=True),
        ),
    ]
