# Generated by Django 5.2.1 on 2026-09-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0189_alter_reporteguardia_proviene'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevacaciones',
            name='tipo',
            field=models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('BACKUP', 'Backup')], db_index=True, default='VACACIONES', max_length=12),
        ),
    ]
