# Generated by Django 5.2.1 on 2026-09-29 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0191_sacafrancoasistencia_persona_cobertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasEventual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('horas', models.PositiveSmallIntegerField()),
                ('horas_adicionales', models.PositiveSmallIntegerField(default=0)),
                ('valor_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='CoreFisica.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='CoreFisica.instalacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_eventual', to='CoreFisica.persona')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CoreFisica.puesto')),
            ],
            options={
                'verbose_name': 'Horas de eventual',
                'verbose_name_plural': 'Horas de eventuales',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
