# Generated by Django 5.2.1 on 2026-09-29 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0192_horaseventual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horaseventual',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HorasEventualHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('MODIFICADO', 'Modificado')], max_length=12)),
                ('usuario_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('persona', models.CharField(blank=True, default='', max_length=200)),
                ('cliente', models.CharField(blank=True, default='', max_length=200)),
                ('instalacion', models.CharField(blank=True, default='', max_length=200)),
                ('puesto', models.CharField(blank=True, default='', max_length=200)),
                ('horas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('horas_adicionales', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valor_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='CoreFisica.horaseventual')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_en', 'id'],
            },
        ),
    ]
