# Generated by Django 5.2.1 on 2026-09-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0193_horaseventual_modificado_por_horaseventualhistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaseventual',
            name='bonificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='horaseventual',
            name='horas_solicitadas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='horaseventualhistorial',
            name='bonificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='horaseventualhistorial',
            name='horas_solicitadas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
