# Generated by Django 5.2.1 on 2026-09-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0194_horaseventual_bonificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaseventual',
            name='rango_horas',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='horaseventualhistorial',
            name='rango_horas',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
