# Generated by Django 5.2.1 on 2026-09-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0195_horaseventual_rango_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaseventual',
            name='valor_manual',
            field=models.BooleanField(default=False),
        ),
    ]
