# Generated by Django 5.2.1 on 2026-09-29 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0196_horaseventual_valor_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaseventual',
            name='cliente_texto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='horaseventual',
            name='instalacion_texto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='horaseventual',
            name='puesto_texto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='horaseventual',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='CoreFisica.cliente'),
        ),
        migrations.AlterField(
            model_name='horaseventual',
            name='instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='CoreFisica.instalacion'),
        ),
    ]
