# Generated by Django 5.2.1 on 2026-09-30 19:10

"""Permiso propio para la campanita (puestos sin persona): view_notificacion_vacantes.
Para que nadie la pierda al desplegar, se da a los grupos y usuarios que hoy tienen
view_asignacion (los que ya la veían). Después se quita a quien no la necesite."""
from django.db import migrations


def dar_a_quienes_la_veian(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')
    ct, _ = ContentType.objects.get_or_create(app_label='CoreFisica', model='asignacion')
    nuevo, _ = Permission.objects.get_or_create(
        content_type=ct, codename='view_notificacion_vacantes',
        defaults={'name': 'Can view notificacion de puestos sin persona'})
    ver = Permission.objects.filter(content_type=ct, codename='view_asignacion').first()
    if not ver:
        return
    for g in Group.objects.filter(permissions=ver):
        g.permissions.add(nuevo)
    for u in User.objects.filter(user_permissions=ver):
        u.user_permissions.add(nuevo)


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0199_banco_solo_entidad_mayusculas'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'permissions': [('export_asignacion', 'Can export asignacion'), ('import_puestos_asignaciones', 'Can import puestos/asignaciones'), ('view_notificacion_vacantes', 'Can view notificacion de puestos sin persona')]},
        ),
        migrations.RunPython(dar_a_quienes_la_veian, migrations.RunPython.noop),
    ]
