# Generated by Django 5.2.1 on 2026-10-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0200_permiso_notificacion_vacantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGuardiaOculta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('seccion', models.CharField(max_length=15)),
                ('persona_id_ref', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reporte_asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardia_ocultas', to='CoreFisica.reporteasistencia')),
                ('sacafranco_fila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardia_ocultas', to='CoreFisica.sacafrancofila')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'seccion'], name='CoreFisica__fecha_3e5198_idx')],
            },
        ),
    ]
