# Generated by Django 5.2.1 on 2026-10-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0201_reporte_guardia_oculta'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaseventual',
            name='turno',
            field=models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], db_index=True, default='Diurno', max_length=8),
        ),
    ]
