# Generated by Django 5.2.1 on 2026-10-06 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0203_reportevacaciones_tipo_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='radio_m',
            field=models.PositiveSmallIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='ubicacion_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VisitaSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_cliente', models.UUIDField(unique=True)),
                ('fecha_hora', models.DateTimeField()),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('precision_m', models.FloatField(blank=True, null=True)),
                ('distancia_m', models.FloatField(blank=True, null=True)),
                ('estado_gps', models.CharField(choices=[('OK', 'Dentro del puesto'), ('PRECISION_BAJA', 'Precisión baja'), ('FUERA_DE_RANGO', 'Fuera de rango'), ('SIN_UBICACION_PUESTO', 'El puesto aún no tiene ubicación confirmada'), ('SIN_GPS', 'Sin GPS')], db_index=True, default='SIN_GPS', max_length=24)),
                ('nota', models.TextField(blank=True, default='')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='CoreFisica.instalacion')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='CoreFisica.puesto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita de supervisor',
                'verbose_name_plural': 'Visitas de supervisores',
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
    ]
