# Generated by Django 5.2.1 on 2026-10-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0205_permisos_vacaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteasistenciahistorial',
            name='turno',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
    ]
