# Generated by Django 5.2.1 on 2026-10-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0206_historial_turno_24h'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sacafrancoasistencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sacafrancoasistencia',
            name='turno',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sacafrancoasistenciahistorial',
            name='turno',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='sacafrancoasistencia',
            unique_together={('sacafranco_fila', 'fecha', 'turno')},
        ),
    ]
