# Generated by Django 5.2.1 on 2026-10-08 14:37

from django.db import migrations

# Servicios Adicionales tiene ahora su PROPIO permiso de solo lectura (view_servicioadicional). Para que nadie
# pierda acceso, se entrega a los grupos y usuarios que hoy ven el Reporte de Guardia (antes el módulo usaba ese
# permiso). Después se quita o se da desde el admin.
CODENAME = 'view_servicioadicional'


def asignar(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')
    guardia = Permission.objects.filter(content_type__app_label='CoreFisica', codename='view_reporteguardia').first()
    if not guardia:
        return                      # base nueva: los permisos aún no existen (se crean después)
    ct, _ = ContentType.objects.get_or_create(app_label='CoreFisica', model='servicioadicional')
    perm, _ = Permission.objects.get_or_create(content_type=ct, codename=CODENAME,
                                               defaults={'name': 'Can view servicio adicional'})
    for g in Group.objects.filter(permissions=guardia):
        g.permissions.add(perm)
    for u in User.objects.filter(user_permissions=guardia):
        u.user_permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0207_sacafranco_turno_24h'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
            ],
            options={
                'verbose_name': 'servicio adicional',
                'verbose_name_plural': 'servicios adicionales',
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
                'constraints': [],
            },
            bases=('CoreFisica.reporteguardia',),
        ),
        migrations.RunPython(asignar, migrations.RunPython.noop),
    ]
