# Generated by Django 5.2.1 on 2026-10-08 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Servicios Adicionales pasa a ser un FORMULARIO propio (formato FR-REPORTE DE PUESTO ADICIONAL), con su tabla.
# Se conserva el permiso de ver (view_servicioadicional). Crear y editar se dan a quien hoy marca la asistencia
# (change_reporteasistencia: Consola). El permiso del PRECIO no se da a nadie: se asigna desde el admin.


def asignar(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')
    marca = Permission.objects.filter(content_type__app_label='CoreFisica',
                                      codename='change_reporteasistencia').first()
    if not marca:
        return                      # base nueva: los permisos aún no existen (se crean después)
    ct, _ = ContentType.objects.get_or_create(app_label='CoreFisica', model='servicioadicional')
    nuevos = [Permission.objects.get_or_create(content_type=ct, codename=c, defaults={'name': n})[0]
              for c, n in (('view_servicioadicional', 'Can view servicio adicional'),
                           ('add_servicioadicional', 'Can add servicio adicional'),
                           ('change_servicioadicional', 'Can change servicio adicional'))]
    Permission.objects.get_or_create(content_type=ct, codename='editar_precio_servicioadicional',
                                     defaults={'name': 'Puede poner el precio del servicio adicional'})
    for g in Group.objects.filter(permissions=marca):
        g.permissions.add(*nuevos)
    for u in User.objects.filter(user_permissions=marca):
        u.user_permissions.add(*nuevos)


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0208_permiso_servicios_adicionales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicioAdicional',
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('turno', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], default='Diurno', max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('horas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('solicitado_por', models.CharField(blank=True, default='', max_length=150)),
                ('recibido_por', models.CharField(blank=True, default='', max_length=150)),
                ('medio', models.CharField(blank=True, default='', max_length=100)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_adicionales', to='CoreFisica.asignacion')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_adicionales', to='CoreFisica.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_adicionales', to='CoreFisica.instalacion')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sacafranco_fila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_adicionales', to='CoreFisica.sacafrancofila')),
            ],
            options={
                'verbose_name': 'servicio adicional',
                'verbose_name_plural': 'servicios adicionales',
                'ordering': ['fecha', 'turno', 'id'],
                'permissions': [('editar_precio_servicioadicional', 'Puede poner el precio del servicio adicional')],
                'default_permissions': ('view', 'add', 'change'),
                'indexes': [models.Index(fields=['fecha', 'turno'], name='CoreFisica__fecha_cccdc4_idx')],
            },
        ),
        migrations.RunPython(asignar, migrations.RunPython.noop),
    ]
