# Generated by Django 5.2.1 on 2026-10-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0209_servicio_adicional_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaseventual',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='horaseventualhistorial',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
