# Generated by Django 5.2.1 on 2026-10-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreFisica', '0210_motivo_eventual'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteguardia',
            name='servicio_adicional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filas_guardia', to='CoreFisica.servicioadicional'),
        ),
        migrations.AddField(
            model_name='servicioadicional',
            name='cliente_texto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servicioadicional',
            name='instalacion_texto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servicioadicional',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_adicionales', to='CoreFisica.persona'),
        ),
        migrations.AddField(
            model_name='servicioadicional',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_adicionales', to='CoreFisica.puesto'),
        ),
        migrations.AddField(
            model_name='servicioadicional',
            name='puesto_texto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
